### ISSUE TITLE
NO node Found For fail-over in the main segment

### ISSUE THREAD

**Issue by balbaev** [Tusamarco/pxc_scheduler_handler#25]
Explain please what is mainSegment and activeFailover means?
I've got error from the caption with the following setup:

+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| hostgroup_id | hostname     | port | gtid_port | status       | weight | compression | max_connections | max_replication_lag | use_ssl | max_latency_ms | comment |
+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+
| 3            | 10.250.1.226 | 3306 | 0         | OFFLINE_SOFT | 102    | 0           | 200             | 0                   | 1       | 0              |         |
| 1            | 10.250.1.226 | 3306 | 0         | OFFLINE_SOFT | 102    | 0           | 200             | 0                   | 1       | 0              |         |
| 8003         | 10.250.2.20  | 3306 | 0         | ONLINE       | 34     | 0           | 200             | 0                   | 1       | 0              |         |
| 8003         | 10.250.2.0   | 3306 | 0         | ONLINE       | 29     | 0           | 200             | 0                   | 1       | 0              |         |
| 8003         | 10.250.1.226 | 3306 | 0         | SHUNNED      | 102    | 0           | 200             | 0                   | 1       | 0              |         |
| 8001         | 10.250.2.20  | 3306 | 0         | ONLINE       | 31     | 0           | 200             | 0                   | 1       | 0              |         |
| 8001         | 10.250.2.0   | 3306 | 0         | ONLINE       | 99     | 0           | 200             | 0                   | 1       | 0              |         |
| 8001         | 10.250.1.226 | 3306 | 0         | SHUNNED      | 102    | 0           | 200             | 0                   | 1       | 0              |         |
| 3            | 10.250.2.20  | 3306 | 0         | ONLINE       | 66     | 0           | 200             | 0                   | 1       | 0              |         |
| 3            | 10.250.2.0   | 3306 | 0         | ONLINE       | 92     | 0           | 200             | 0                   | 1       | 0              |         |
+--------------+--------------+------+-----------+--------------+--------+-------------+-----------------+---------------------+---------+----------------+---------+

hostgroup 1 is writer hostgroup
hostgroup 3 is reader hostgroup

**Comment by Tusamarco** [comment]
hi @balbaev 
The tool is Galera segment aware. This means that if you define your cluster to use different segments, in the tool you can define which of them is the main one.
ie if you have 5 nodes of which 3 are on segment 1, and two on segment 2, and the 3 on segment 1 are the Primary DC, the application needs to refer to segment 1.

in PXC/Galera you can set the segment `wsrep_provider_options = "gmcast.segment=1"` 
given that in your config file you need to set `mainSegment=N` where N is the segment define in the gmcast.segment (0 is the default).
`activeFailover` refer to the capability of the app to fail-over one of the backup nodes. Currently supported only 0 and 1 meaning, do not perform fail-over or do the fail-over. 
This setting in the previous script (https://github.com/Tusamarco/proxy_sql_tools) had 0|1|2 but apparently the value 2 (fail-over to a different segment) was almost never used, and given it requires some additional workload I have removed it for the moment.

Let me know if this explain enough

**Comment by balbaev** [comment]
Thank you for explanation @Tusamarco 
I have 3 nodes on the same segment (gmcast.segment = 0) with mainSegment = 0, but I still get the following error in case of failover:
`[ERROR]:2021-05-07 09:45:57 - !!!!!!!!!!!!!!! NO node Found For fail-over in the main segment 0 you may want to use ActiveFailover = 2 if you have another node in a different segment  !!!!!!!!!!!!!
[ERROR]:2021-05-07 09:45:57 - Error electing Node for fail-over`
There are 2 other ONLINE nodes in a backup writer hostgroup on the same segment.
How can i debug it?

**Comment by Tusamarco** [comment]
try :
```
[global]
debug = true
```
and check the scheduler log 
can u share also the config file you are using please

**Comment by balbaev** [comment]
scheduler log:
```[DEBUG]:2021-05-07 10:30:37 - Testing the log
[INFO]:2021-05-07 10:30:37 - Testing the log
[WARNING]:2021-05-07 10:30:37 - Testing the log
[ERROR]:2021-05-07 10:30:37 - testing log errors
[DEBUG]:2021-05-07 10:30:37 - Log initialized
[INFO]:2021-05-07 10:30:37 - Locker initialized
[DEBUG]:2021-05-07 10:30:37 - Using lock ID: #LOCK_1_HG_1_W_HG_3_R_
[DEBUG]:2021-05-07 10:30:37 - Locker time: 1620383437639832363
[DEBUG]:2021-05-07 10:30:37 - Cluster Node 10.250.1.226:6032 has a scheduler lock 
[DEBUG]:2021-05-07 10:30:37 - Lock acquired by node 10.250.1.226:6032 Current time 1620383437639832363
[DEBUG]:2021-05-07 10:30:37 - ProxySQL node initialized 
[DEBUG]:2021-05-07 10:30:37 - Cluster arguments  clusterid=1 hg_w:1 hg_r:3 bckhg_w:8001 bckhg_w:8003 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:2000 main_segment:0
[DEBUG]:2021-05-07 10:30:37 - Retrieving information from node: 10.250.1.226:3306
[DEBUG]:2021-05-07 10:30:37 - Retrieving information from node: 10.250.2.20:3306
[DEBUG]:2021-05-07 10:30:37 - Retrieving information from node: 10.250.2.0:3306
[ERROR]:2021-05-07 10:30:37 - dial tcp 10.250.1.226:3306: connect: connection refused
[WARNING]:2021-05-07 10:30:37 - Cannot load information (variables/status/pxc_view) for node: 10.250.1.226:3306
[DEBUG]:2021-05-07 10:30:37 - node 10.250.1.226:3306 done
[DEBUG]:2021-05-07 10:30:37 - node 10.250.2.20:3306 done
[DEBUG]:2021-05-07 10:30:37 - node 10.250.2.0:3306 done
[DEBUG]:2021-05-07 10:30:37 - time taken :22 checkTimeOut : 2000
[DEBUG]:2021-05-07 10:30:37 - PXC cluster data nodes initialized 
[DEBUG]:2021-05-07 10:30:37 - Evaluating node 3_10.250.2.0:3306
[DEBUG]:2021-05-07 10:30:37 - Evaluating node 3_10.250.1.226:3306
[DEBUG]:2021-05-07 10:30:37 - Evaluating node 1_10.250.1.226:3306
[DEBUG]:2021-05-07 10:30:37 - Evaluating node 3_10.250.2.20:3306
[DEBUG]:2021-05-07 10:30:37 - Node 10.250.1.226:3306 is not in ONLINE state in writer HG 1 removing while evaluating
[ERROR]:2021-05-07 10:30:37 - !!!!!!!!!!!!!!! NO node Found For fail-over in the main segment 0 you may want to use ActiveFailover = 2 if you have another node in a different segment  !!!!!!!!!!!!!
[ERROR]:2021-05-07 10:30:37 - Error electing Node for fail-over
[INFO]:2021-05-07 10:30:37 - Processing action node list and build SQL commands
[INFO]:2021-05-07 10:30:37 - Connection close
[INFO]:2021-05-07 10:30:37 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2021-05-07 10:30:37 - Phase: main = 72,115,471 us 72 ms
[INFO]:2021-05-07 10:30:37 - Phase: Cluster lock = 39,058,768 us 39 ms
[INFO]:2021-05-07 10:30:37 - Phase: proxysql_init = 1,972,631 us 1 ms
[INFO]:2021-05-07 10:30:37 - Phase: main_connection = 1,114,390 us 1 ms
[INFO]:2021-05-07 10:30:37 - Phase: Execute SQL changes - ProxySQL cluster LOCK (1_HG_1_W_HG_3_R) = 32,524,463 us 32 ms
[INFO]:2021-05-07 10:30:37 - Phase: data_cluster_init = 29,938,152 us 29 ms
[INFO]:2021-05-07 10:30:37 - Phase: loadNodes = 5,935,213 us 5 ms
[INFO]:2021-05-07 10:30:37 - Phase: Get info for node 10.250.1.226:3306 = -1,620,383,437,680,895,866 us -1620383437680 ms
[INFO]:2021-05-07 10:30:37 - Phase: node_connection_10.250.1.226:3306 = -1,620,383,437,680,897,402 us -1620383437680 ms
[INFO]:2021-05-07 10:30:37 - Phase: Get info for node 10.250.2.0:3306 = 21,329,122 us 21 ms
[INFO]:2021-05-07 10:30:37 - Phase: node_connection_10.250.2.0:3306 = 15,255,820 us 15 ms
[INFO]:2021-05-07 10:30:37 - Phase: Get info for node 10.250.2.20:3306 = 20,599,022 us 20 ms
[INFO]:2021-05-07 10:30:37 - Phase: node_connection_10.250.2.20:3306 = 14,718,493 us 14 ms
[INFO]:2021-05-07 10:30:37 - Phase: Get Action Map (DataCluster) = 692,384 us 0 ms
[INFO]:2021-05-07 10:30:37 - Phase: Process changes - ActionMap - (ProxysqlNode) = 62,869 us 0 ms
```


config:
```[pxccluster]
activeFailover = 1
failBack = false
checkTimeOut = 2000
# debug = 1 //Deprecated: this is redundant and not in use
mainSegment = 0
#sslClient = "client-cert.pem"
#sslKey = "client-key.pem"
#sslCa = "ca.pem"
#sslCertificatePath = "/opt/cert/ssl_test"
hgW = 1
hgR = 3
bckHgW = 8001
bckHgR = 8003
singlePrimary = true
maxNumWriters = 1
writerIsAlsoReader = 1
retryUp = 0
retryDown = 2
clusterId = 1


[proxysql]
port = 6032
host = "10.250.1.226"
user = "clusteradmin"
password = "password"
clustered = true
lockfilepath ="/var/run/proxysql_scheduler"


[global]
debug = true
logLevel = "debug"
logTarget = "file" #stdout | file
logFile = "/var/log/proxysql_scheduler/pscheduler.log"
daemonize = false
daemonInterval = 2000
performance = true
OS = "na"
lockfiletimeout = 60 #seconds
lockclustertimeout = 600 #120 # seconds```

**Comment by Tusamarco** [comment]
Permission issues:
```
DEBUG]:2021-05-07 10:30:37 - Retrieving information from node: 10.250.2.0:3306
[ERROR]:2021-05-07 10:30:37 - dial tcp 10.250.1.226:3306: connect: connection refused
[WARNING]:2021-05-07 10:30:37 - Cannot load information (variables/status/pxc_view) for node: 10.250.1.226:3306
[DEBUG]:2021-05-07 10:30:37 - node 10.250.1.226:3306 done
```

Please check the user used by Proxysql to connect to the nodes ie in my case:
```
(root@localhost) [(none)]>show grants for monitor@'%';
+---------------------------------------------------------+
| Grants for monitor@%                                    |
+---------------------------------------------------------+
| GRANT USAGE ON *.* TO `monitor`@`%`                     |
| GRANT SELECT ON `performance_schema`.* TO `monitor`@`%` |
+---------------------------------------------------------+
2 rows in set (0.00 sec)

```

**Comment by Tusamarco** [comment]
And yes ....
I forgot the to add the security instructions to the readme, my fault.

**Comment by balbaev** [comment]
The user has appropriate permissions. The node 10.250.1.226 was intentionally shutted down due to check failover.

**Comment by Tusamarco** [comment]
Then check the status of the remaining nodes. Probably they have one of the conditions :
```
Node states:

pxc_main_mode
read_only
wsrep_status
wsrep_rejectqueries
wsrep_donorrejectqueries
wsrep_connected
wsrep_desinccount
wsrep_ready
wsrep_provider
wsrep_segment
Number of nodes in by segment
Retry loop
PXC cluster state
```
that is preventing the usage as writer. 
try to capture the status (global) and share let see what is going on

**Comment by Tusamarco** [comment]
Please add also show global variables; show global status;

**Comment by balbaev** [comment]
10.250.2.20 global status:
https://xpaste.pro/p/AtA83IIP

10.250.2.20 global variables:
https://xpaste.pro/p/GRB6FfIX

10.250.2.0 global status:
https://xpaste.pro/p/7YfwbFbn

10.250.2.0 global variables:
https://xpaste.pro/p/pg1CvkTY

**Comment by Tusamarco** [comment]
@balbaev you have the read nodes with:
`read_only	ON` that obviously prevent to pick them as writers
ProxySQL or the pxc_scheduler_handler will never change the state of a node in the node.

**Comment by balbaev** [comment]
@Tusamarco thank you so much, resolved
