### ISSUE TITLE
Add support to manage multiple ProxySQL instances with a handler instance

### ISSUE THREAD

**Issue by markusalbe** [Tusamarco/pxc_scheduler_handler#29]
Allowing a single handler to push reconfigurations into multiple proxies allows for centralized management (desirable by some customers) and also saves the PXC nodes from being bombarded by all the healthchecks from multiple handler instances.

**Comment by Tusamarco** [comment]
@markusalbe, no this go against the basic concept of the tool to work in full isolation on one cluster. Wondering how many customers have many (where many is > 10) PXC cluster under one single Proxysql.  With the lock in place FR 27, you will be able to deal with multiple pxc cluster. The impact or load on ProxySQL is really minimal and I do not see it as an issue.

**Comment by Tusamarco** [comment]
closing given no further comments
